### PR TITLE
New translations strings.po (Portuguese)

### PR DESCRIPTION
**Pull request by Blackspirits**

### CODE REVIEW

**Comment by Simkl-dev** [comment]
Please use https://crowdin.com/project/Kodi-add-on-for-Simkl to submit translations

**Comment by Blackspirits** [comment]
I changed were not translation, because the already had a few months ago by CrowdIn. it was just information that can't be updated by crowdin

**Comment by Simkl-dev** [comment]
We've pushed an update with updated translations 2 weeks ago into kodi, update your kodi plugin. I'm afraid your changes to the file will break Crowdin integration.

**Comment by Simkl-dev** [comment]
https://github.com/xbmc/repo-scripts/pull/1190

**Comment by Simkl-dev** [comment]
You cannot change the "Project-Id-Version: Kodi-add-on-for-Simkl\n"

**Comment by Simkl-dev** [comment]
Could you please DM Andrew on Discord https://discord.gg/u89XfYn and explain what kind of issues you have that were changed in the language file.

**Pull request closed without merging**
